from app.semantic.models.semantic_types import SemanticType


SEMANTIC_TYPES = [
    SemanticType(
        semantic_type_id="PURCHASE",
        name="Purchase",
        is_terminal_spending=True,
        requires_allocation=False,
        exclude_from_spending_reports=False,
        is_income=False,
        is_transfer=False,
    ),
    SemanticType(
        semantic_type_id="ATM_WITHDRAWAL",
        name="ATM Withdrawal",
        is_terminal_spending=False,
        requires_allocation=True,
        exclude_from_spending_reports=False,
        is_income=False,
        is_transfer=False,
    ),
    SemanticType(
        semantic_type_id="INTERNAL_TRANSFER",
        name="Internal Transfer",
        is_terminal_spending=False,
        requires_allocation=False,
        exclude_from_spending_reports=True,
        is_income=False,
        is_transfer=True,
    ),
    SemanticType(
        semantic_type_id="PEER_TRANSFER",
        name="Peer Transfer",
        is_terminal_spending=False,
        requires_allocation=False,
        exclude_from_spending_reports=False,
        is_income=False,
        is_transfer=True,
    ),
    SemanticType(
        semantic_type_id="SAVINGS_TRANSFER",
        name="Savings Transfer",
        is_terminal_spending=False,
        requires_allocation=False,
        exclude_from_spending_reports=True,
        is_income=False,
        is_transfer=True,
    ),
    SemanticType(
        semantic_type_id="SALARY",
        name="Salary",
        is_terminal_spending=False,
        requires_allocation=False,
        exclude_from_spending_reports=False,
        is_income=True,
        is_transfer=False,
    ),
    SemanticType(
        semantic_type_id="REFUND",
        name="Refund",
        is_terminal_spending=False,
        requires_allocation=False,
        exclude_from_spending_reports=False,
        is_income=False,
        is_transfer=False,
    ),
    SemanticType(
        semantic_type_id="FEE",
        name="Fee",
        is_terminal_spending=True,
        requires_allocation=False,
        exclude_from_spending_reports=False,
        is_income=False,
        is_transfer=False,
    ),
    SemanticType(
        semantic_type_id="UNKNOWN",
        name="Unknown",
        is_terminal_spending=False,
        requires_allocation=False,
        exclude_from_spending_reports=False,
        is_income=False,
        is_transfer=False,
    ),
]